### ISSUE TITLE
Installing a Moodle plugin fails due to write permissions

### ISSUE THREAD

**Issue by k-markov** [bitnami/bitnami-docker-moodle#64] opened 2017-09-12 09:40 UTC
**Description**
Hi,
Tried to install the Attendance [plugin](https://moodle.org/plugins/download.php/14023/mod_attendance_moodle33_2017050204.zip) but got write permission error to folder /opt/bitnami/moodle/mod. As a temporal workaround, changed the write permissions of that folder to "g+w" and then plugin installed normally. It turns out that the owner of /opt/bitnami/moodle/mod is bitnami:daemon, but the owner of the newly created folder  /opt/bitnami/moodle/mod/attendance is daemon:daemon. Apparently, the application is started by user daemon and this creates the write permission issue.

**Steps to reproduce the issue:**

1. Download the plugin zip file.
2. Login as admin user.
3. Go to manual plugin installation page.
4. Drag and drop the zip file into that page.
5. Start plugin install.

**Describe the results you received:**

Write permission error to folder /opt/bitnami/moodle/mod is displayed.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63GiB
Name: hi-srv2
ID: 7C6V:IHFG:344I:7OO6:VWCJ:OG5Q:BJM5:LOAN:5UG2:K75C:QW5D:P2CF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.15.0, build e12f3b9
docker-py version: 2.4.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment] 2017-09-18 14:35
Hi @k-markov,

Thanks for reporting this, we can reproduce the issue.

We will work on a fix for this issue and we will update our Docker image for moodle.

Thanks again!

**Comment by burkeallen** [comment] 2017-12-19 21:13
Just pulled the latest docker images, and I am experiencing the same issue with trying to install a plugin, is there any update on correcting this in the image file? or is there a workaround for this until it can be corrected?

**Comment by javsalgar** [comment] 2017-12-20 12:34
Hi @burkeallen 

I was unable to reproduce it. I just installed a plugin without issues. 

<img width="686" alt="screen shot 2017-12-20 at 13 32 20" src="https://user-images.githubusercontent.com/1133777/34207359-6d5b5786-e58a-11e7-89c6-e188ca2b2fb9.png">

Could you provide more information on how to reproduce it?

**Comment by burkeallen** [comment] 2017-12-20 13:20
Done git repo, run docker compose up, install plugin. Fails every time.

I worked around it by mounting the plugin directory to a local host
directory, which in windows hosts makes permissions fully rwx.

**Comment by javsalgar** [comment] 2017-12-21 10:38
Hi,

You said you cloned the git repo, but did you have the plugin volume already created? Did it fail with the exact default configuration? (i.e. you did not have an external folder that you were mounting).

In addition, are you using Docker for Windows? Because I tested it with Docker for Mac and docker for Linux. Maybe it is a bug in Docker for Windows regarding the permissions.

**Comment by burkeallen** [comment] 2017-12-21 12:26
I did not have the plugin volume already created and yes I am using docker
for windows.



On Dec 21, 2017 5:38 AM, "Javier J. Salmerón-García" <
notifications@github.com> wrote:

Hi,

You said you cloned the git repo, but did you have the plugin volume
already created? Did it fail with the exact default configuration? (i.e.
you did not have an external folder that you were mounting).

In addition, are you using Docker for Windows? Because I tested it with
Docker for Mac and docker for Linux. Maybe it is a bug in Docker for
Windows regarding the permissions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitnami/bitnami-docker-moodle/issues/64#issuecomment-353318212>,
or mute the thread

**Comment by andresbono** [comment] 2017-12-28 12:00
Hi @burkeallen, which plugin are you trying to install? With that information we can try to reproduce the issue and update our image if needed.

Thanks!

**Comment by burkeallen** [comment] 2017-12-28 13:44
The Logstore xAPI

https://moodle.org/plugins/logstore_xapi





*Burke Allen*
*NovoLogic, Inc*
*mobile 770-265-4362 *

**Comment by andresbono** [comment] 2017-12-29 10:48
Hi @burkeallen,

Thanks for the information. We can reproduce a permissions issue when trying to install the _Logstore xAPI_ plugin:

```
Validating logstore_xapi ... Error
  [Error] Write access check [/opt/bitnami/moodle/admin/tool/log/store] 
Installation aborted due to validation failure
```

As a workaround,  you can fix this by executing the following commands inside the container:

```
mv /opt/bitnami/moodle/admin/tool/log/store /bitnami/moodle/
ln -s /bitnami/moodle/store /opt/bitnami/moodle/admin/tool/log/store
chown daemon /bitnami/moodle/store
```
Hope it helps.

Regards,

**Comment by marcosbc** [comment] 2020-07-20 23:08
Hi, we recently refactored the bootstrap logic for the Moodle container. For more info see: https://github.com/bitnami/bitnami-docker-moodle#390-debian-10-r17

We believe this should not be an issue anymore, so I'll proceed to close this issue. But if you are still finding related problems, let us know and we can re-open this.

**Closed by marcosbc** 2020-07-20 23:08 UTC
Labels: on-hold

**Comment by VCOSTA-Dev** [comment] 2020-08-19 14:05
> Hi @burkeallen,
> 
> Thanks for the information. We can reproduce a permissions issue when trying to install the _Logstore xAPI_ plugin:
> 
> ```
> Validating logstore_xapi ... Error
>   [Error] Write access check [/opt/bitnami/moodle/admin/tool/log/store] 
> Installation aborted due to validation failure
> ```
> 
> As a workaround, you can fix this by executing the following commands inside the container:
> 
> ```
> mv /opt/bitnami/moodle/admin/tool/log/store /bitnami/moodle/
> ln -s /bitnami/moodle/store /opt/bitnami/moodle/admin/tool/log/store
> chown daemon /bitnami/moodle/store
> ```
> 
> Hope it helps.
> 
> Regards,

it worked perfectly for me.
Thanks
