### ISSUE TITLE
STARTTLS failed - LDAPS with IPA server 

### ISSUE THREAD

**Issue by rustamabdullin** [bitnami/bitnami-docker-moodle#94] opened 2019-07-01 10:25 UTC
**Unable to connect to IPA server via 636 port / LDAPS. IPA server uses Let's encrypt trusted certificate**

**Steps to reproduce the issue:**

1. Deploy moodle using docker compose
2. Setup with 389 port (everything is fine here)
3. Change LDAP server to ldaps://

**Describe the results you received:**

Scheduled task failed: LDAP users sync job (auth_ldap\task\sync_task),LDAP-module cannot connect to any servers: Server: 'ipa.local.net', Connection: 'Resource id #608', STARTTLS failed.

Deferentially not a network issue.

Should I mount something like this?

```
/etc/ldap/ldap.conf:

TLS_REQCERT never
```

**Describe the results you expected:**

Successful LDAPS connection.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Latest version of image, docker and docker-compose.

**Comment by rustamabdullin** [comment] 2019-07-01 10:52
Solved with following settings:

Host URL: ldaps://server.local:636

Use TLS: No

**Comment by andresbono** [comment] 2019-07-02 06:34
Hi @rustamabdullin, thanks for letting us know that the issue is solved and posting your solution. We are closing it.

**Closed by andresbono** 2019-07-02 06:34 UTC
