### ISSUE TITLE
Apache stops working just after successfull installation of moodle 

### ISSUE THREAD

**Issue by gungam** [bitnami/bitnami-docker-moodle#111] opened 2020-04-07 21:05 UTC
I tried to install the latest (3.8.2 debian 10 r25) on my synology NAS.
Im running MariaDB 10 direct on the NAS (not in a docker) 
I tried it a couple of times with minor changes but it ends every time with the following messages in the log file:

>...
>nami    INFO  moodle successfully initialized 
>INFO  ==> Starting gosu... 
>Starting Apache...
>[Tue Apr 07 20:47:58.471685 2020] [:crit] [pid 99] (38)Function not implemented: AH00141: Could not initialize random number generator

**Comment by Mauraza** [comment] 2020-04-08 08:10
Hi @gungam,

Have you added any extra settings in addition to the database?

**Comment by gungam** [comment] 2020-04-09 13:26
Hello Mauraza,

i made the following settings:
- mounted the /bitnami folder in the docker-system to a local path. 
- forwarded the local system ports 10443 and 10080 to the docker system at 80 and 443
- and set the following variables:
MARIADB_HOST = 192.168.XXX.XXX 
MARIADB_PORT_NUMBER = 3307
MARIADB_ROOT_PASSWORD = ***
MOODLE_DATABASE_PASSWORD = ***
MOODLE_USERNAME = ***
MYSQL_CLIENT_CREATE_DATABASE_NAME = bitnami_moodle
MYSQL_CLIENT_CREATE_DATABASE_PASSWORD = ***
MYSQL_CLIENT_CREATE_DATABASE_USER = moodle_bn

All other settings are untouched with the default settings.

**Comment by Mauraza** [comment] 2020-04-09 14:21
Could you activate the debug in docker and add the log to the thread?

**Comment by gungam** [comment] 2020-04-09 21:23
I started the container with "docker -D -l debug start bitnami-moodle1"
but the logfile does not show any relevant news:

> Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
Send us your feedback at containers@bitnami.com

>INFO  ==> Starting gosu... 
Starting Apache...
[Thu Apr 09 21:18:06.986888 2020] [:crit] [pid 56] (38)Function not implemented: AH00141: Could not initialize random number generator

**Comment by gungam** [comment] 2020-04-10 00:00
Tried an older version of this docker (3.7.2-debian-9-r46) with nearly the same parameters. it runs clean through the setup process and i can access the moodle start page. 
I will try to update the system tomorrow. 
So it seems to be a problem with the newer versions of this docker.

**Comment by Mauraza** [comment] 2020-04-10 07:18
I hope the update fixes it.

**Comment by gungam** [comment] 2020-04-10 21:40
Tried to update the docker according to https://github.com/bitnami/bitnami-docker-moodle#upgrade-this-application.
Sadly the same error (AH00141: Could not initialize random number generator) appears and the docker immediately stops.
Went back to the old system and everything works again. 
I still assume a problem with the latest versions.

**Comment by Mauraza** [comment] 2020-04-13 14:07
Hi @gungam 

I haven't been able to replicate the issue. But I've done some research that could prove it:
- check the path no have any invalid character.
- update the libraries of your operating system.

**Comment by Jefferson-goxts** [comment] 2020-04-27 18:31
I got the same error, im using this container:
https://github.com/bitnami/bitnami-docker-moodle
https://github.com/bitnami/bitnami-docker-mariadb


date | stream | content
-- | -- | --
2020-04-27 07:05:33 | stdout | [Mon Apr 27 07:05:33.067502 2020] [:crit] [pid 90] (38)Function not implemented: AH00141: Could not initialize random number generator
2020-04-27 07:05:32 | stdout | Starting Apache...
2020-04-27 07:05:32 | stdout | [0m[38;5;2mINFO [0m ==> Starting gosu...
2020-04-27 07:05:32 | stdout | [37mnami   [39m [32mINFO [39m moodle successfully initialized
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m ########################################################################
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m  (Passwords are not shown for security reasons)
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m    Email: user@example.com
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m    Password: **********
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m    Username: user
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m  Installation parameters for moodle:
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m ########################################################################
2020-04-27 07:05:32 | stdout | [36mmoodle [39m [32mINFO [39m
2020-04-27 07:05:24 | stdout | [36mmoodle [39m [32mINFO [39m Configuring Cron Jobs...
2020-04-27 06:41:46 | stdout | [36mmoodle [39m [32mINFO [39m Running Moodle install. Please be patient...
2020-04-27 06:41:46 | stdout | [36mmysql-c[39m [32mINFO [39m MySQL server listening and working at mariadb:3306
2020-04-27 06:41:46 | stdout | [36mmysql-c[39m [32mINFO [39m Found MySQL server listening at mariadb:3306
2020-04-27 06:41:46 | stdout | [36mmysql-c[39m [32mINFO [39m Trying to connect to MySQL server
2020-04-27 06:41:45 | stdout | [36mmoodle [39m [32mINFO [39m Preparing PHP environment...
2020-04-27 06:41:39 | stdout | [37mnami   [39m [32mINFO [39m Initializing moodle
2020-04-27 06:41:32 | stdout | [37mnami   [39m [32mINFO [39m mysql-client successfully initialized
2020-04-27 06:41:32 | stdout | [37mnami   [39m [32mINFO [39m Initializing mysql-client
2020-04-27 06:41:26 | stdout | [37mnami   [39m [32mINFO [39m php successfully initialized
2020-04-27 06:41:26 | stdout | [37mnami   [39m [32mINFO [39m Initializing php
2020-04-27 06:41:20 | stdout | [37mnami   [39m [32mINFO [39m apache successfully initialized
2020-04-27 06:41:20 | stdout | [37mnami   [39m [32mINFO [39m Initializing apache
2020-04-27 06:41:14 | stdout | [0m
2020-04-27 06:41:14 | stdout | [0mSend us your feedback at [1mcontainers@bitnami.com[0m
2020-04-27 06:41:14 | stdout | [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-moodle/issues[0m
2020-04-27 06:41:14 | stdout | [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-moodle[0m
2020-04-27 06:41:14 | stdout | [0m[1mWelcome to the Bitnami moodle container[0m
2020-04-27 06:41:14 | stdout | [0m

**Comment by Mauraza** [comment] 2020-04-28 09:22
Hi @Jefferson-goxts,

Could you please add to the issue the system where are you running the docker-compose?

**Comment by Jefferson-goxts** [comment] 2020-04-29 07:06
Shure, its a NAS from Synology.
DS1817+ DSM 6.2.2-24922 Update 4
(https://www.synology.com/en-global/releaseNote/DS1817+#ver_24922-4)

Docker Daemon to version 18.09.6.
Docker Compose to version 1.24.0.
(https://www.synology.com/de-de/releaseNote/Docker)

**Comment by Mauraza** [comment] 2020-04-29 10:03
Hi @Jefferson-goxts,

Are you checked if there is an invalid character in the path?

**Comment by westveerr** [comment] 2020-05-08 13:39
I have the same issue on debian 8. Locally on my Mac everything is fine.

**Comment by rafariossaa** [comment] 2020-05-11 14:53
Hi,
  I am sorry, DS1817 uses an ARM processor and our container are for AMD64 architectures. 
  @westveerr , Are you facing the same issue on the same hardware ?.

**Comment by rafariossaa** [comment] 2020-05-27 07:38
As there is not more comment on this, I am closing the issue.
Feel free to add a new comment if you consider it.

**Comment by julian3xl** [comment] 2020-11-26 18:45
it happens with all bitnami's apache based images, and it's not fixed, closing not fixed issues looks wrong to me.-

**Comment by rafariossaa** [comment] 2020-11-30 10:28
Hi @julian3xl ,
  Do you mind opening an issue and explain you case there ? We will be glad to help you.
  In this the problem seems to be that they were using images not for their architecture.

**Comment by 3mandd** [comment] 2020-12-03 20:31
[Thu Dec 03 15:26:03.018485 2020] [:crit] [pid 31918] (38)Function not implemented: AH00141: Could not initialize random number generator

 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2

**Comment by 3mandd** [comment] 2020-12-03 20:48
nginx to the rescue! all good now

**Comment by Ray-Eldath** [comment] 2020-12-22 17:18
it still not work on my server, which is a CentOS 7.3

the `kubectl logs phpmyadmin-7cffc54b48-97p6h` returned:

> phpmyadmin 17:07:10.55 INFO  ==> ** Starting Apache **
> [Tue Dec 22 17:07:10.554204 2020] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

---

and, @3mandd, how can nginx solve the problem? sorry but I'm just a newcomer to k8s, helm, bitnami and all sort of things. anything may help will be great. many thx!

**Comment by rafariossaa** [comment] 2020-12-23 09:35
Hi,
  I found this information regarding this issue:
https://bz.apache.org/bugzilla/show_bug.cgi?id=63388
  It seems that could be related to the libs implemented in the server OS and the compilation made.
  @julian3xl , @3mandd are you using centos too ?

**Comment by julian3xl** [comment] 2020-12-23 09:40
In my case ubuntu, osx and synology. It didn't work on none of them.-

**Comment by rafariossaa** [comment] 2020-12-23 09:51
@julian3xl In AMD64 should work (ubuntu, osx), if synology is run on ARM it is not going to work as we don't have ARM based images.
Which error do you have ? Is it the `Could not initialize random number generator` one ? In that case which ubuntu version are you using ?
Could you provide the output of the following commands ?
```
$ lsb_release -d
```

```
$ uname -a
```

**Comment by julian3xl** [comment] 2020-12-23 09:56
My synology is x86_64 ;). And yes, I got that error.

Synology: Linux xxx 3.10.102 #15284 SMP Mon Jul 9 23:04:14 CST 2018 x86_64 GNU/Linux synology_bromolow_3615xs
OSX: Darwin xxx19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
Ubuntu 16.04.5 LTS: Linux xxx 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rafariossaa** [comment] 2020-12-23 10:10
Thank you for the information.
Could you also provide the docker version you are running ? 
I would like to setup a test lab and check I can reproduce the issue.

**Comment by julian3xl** [comment] 2020-12-23 10:36
** Synology:** Docker version 18.09.8, build bfed4f5
**OSX:** Docker version 19.03.13, build 4484c46d9d
**Ubuntu 16.04.5 LTS:** Docker version 19.03.12, build 48a66213fe

**Comment by rafariossaa** [comment] 2020-12-24 12:03
Hi, 
 I did a fresh install of centos 7 + docker + docker-compose , and I was not able to reproduce the issue:
Centos info
```
[rafa@localhost bitnami-docker-moodle]$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

[rafa@localhost bitnami-docker-moodle]$ uname -a
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[rafa@localhost bitnami-docker-moodle]$ docker version
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:37:17 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:35:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Cloning and running moodle compose
```
[rafa@localhost ~]$ git clone https://github.com/bitnami/bitnami-docker-moodle
Cloning into 'bitnami-docker-moodle'...
remote: Enumerating objects: 269, done.
remote: Counting objects: 100% (269/269), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 9207 (delta 82), reused 249 (delta 75), pack-reused 8938
Receiving objects: 100% (9207/9207), 1.08 MiB | 489.00 KiB/s, done.
Resolving deltas: 100% (4006/4006), done.

[rafa@localhost ~]$ cd bitnami-docker-moodle/

[rafa@localhost bitnami-docker-moodle]$ ls
3  docker-compose.yml  LICENSE  README.md

[rafa@localhost bitnami-docker-moodle]$ docker-compose up
Pulling mariadb (docker.io/bitnami/mariadb:10.5-debian-10)...
10.5-debian-10: Pulling from bitnami/mariadb
75ea27cfafcd: Pull complete
5e747e449780: Pull complete
7439928ac91c: Pull complete
b951fe36cc30: Pull complete
86942d7f3fe5: Pull complete
fa50f41f3a38: Pull complete
329482acfe89: Pull complete
308fcd3c8bd1: Pull complete
3b58c7a49729: Pull complete
ffe40c0dc69f: Pull complete
1ac99f3afee3: Pull complete
Digest: sha256:9bfc4390380679aa11aa7c884e85f61766eae398592d81e5c3fef81f64e99c4a
Status: Downloaded newer image for bitnami/mariadb:10.5-debian-10
Pulling moodle (docker.io/bitnami/moodle:3-debian-10)...
3-debian-10: Pulling from bitnami/moodle
75ea27cfafcd: Already exists
a639a8536bc1: Pull complete
328e586ccc44: Pull complete
150b4cdfc4c6: Pull complete
cb65f6b2ea11: Pull complete
7c7a59d55ac7: Pull complete
1c7ed2fdd813: Pull complete
54cf465a1175: Pull complete
835a68ede30b: Pull complete
822b720f25c6: Pull complete
c1422b7a7d6d: Pull complete
738493c90ff2: Pull complete
d40fe8811782: Pull complete
d0abf84e0a64: Pull complete
882902f990dd: Pull complete
d6adcbbfdeff: Pull complete
d0f6b531506c: Pull complete
e55841bb3931: Pull complete
03d54cfcd98b: Pull complete
b3e56d756090: Pull complete
2c35c1aab0e9: Pull complete
a9d305c28083: Pull complete
413ddea94877: Pull complete
b97ed5455b1c: Pull complete
Digest: sha256:091b1820dd0bf543117d3fdeb88de6d03632ab66909ab3fb30e474972d6c40e4
Status: Downloaded newer image for bitnami/moodle:3-debian-10
Creating bitnami-docker-moodle_mariadb_1 ... done
Creating bitnami-docker-moodle_moodle_1  ... done
Attaching to bitnami-docker-moodle_mariadb_1, bitnami-docker-moodle_moodle_1
mariadb_1  | mariadb 11:09:33.21 
mariadb_1  | mariadb 11:09:33.22 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 11:09:33.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | mariadb 11:09:33.22 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 11:09:33.22 
mariadb_1  | mariadb 11:09:33.22 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 11:09:33.24 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 11:09:33.24 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 11:09:33.28 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 11:09:33.31 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1  | mariadb 11:09:33.33 INFO  ==> Setting user option
mariadb_1  | mariadb 11:09:33.41 INFO  ==> Installing database
moodle_1   | moodle 11:09:34.11 
moodle_1   | moodle 11:09:34.11 Welcome to the Bitnami moodle container
moodle_1   | moodle 11:09:34.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1   | moodle 11:09:34.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1   | moodle 11:09:34.11 
moodle_1   | moodle 11:09:34.12 INFO  ==> ** Starting Moodle setup **
moodle_1   | moodle 11:09:34.44 INFO  ==> Configuring PHP options
moodle_1   | moodle 11:09:34.44 INFO  ==> Setting PHP expose_php option
moodle_1   | moodle 11:09:34.48 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 11:09:34.51 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1   | moodle 11:09:34.55 INFO  ==> Ensuring Moodle directories exist
moodle_1   | moodle 11:09:34.57 INFO  ==> Trying to connect to the database server
mariadb_1  | mariadb 11:09:36.97 INFO  ==> Starting mariadb in background
mariadb_1  | mariadb 11:09:39.00 INFO  ==> Configuring authentication
mariadb_1  | mariadb 11:09:39.16 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 11:09:52.53 INFO  ==> Stopping mariadb
mariadb_1  | mariadb 11:09:53.54 INFO  ==> ** MariaDB setup finished! **
mariadb_1  | 
mariadb_1  | mariadb 11:09:53.56 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2020-12-24 11:09:53 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.5.8-MariaDB) starting as process 1 ...
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mariadb_1  | 2020-12-24 11:09:53 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: 128 rollback segments are active.
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: 10.5.8 started; log sequence number 45130; transaction id 20
mariadb_1  | 2020-12-24 11:09:53 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2020-12-24 11:09:53 0 [Note] InnoDB: Buffer pool(s) load completed at 201224 11:09:53
mariadb_1  | 2020-12-24 11:09:53 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2020-12-24 11:09:53 0 [Warning] 'proxies_priv' entry '@% root@c1955c077442' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-12-24 11:09:53 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2020-12-24 11:09:53 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2020-12-24 11:09:53 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.5.8-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
moodle_1   | moodle 11:09:54.69 INFO  ==> Running Moodle install script
moodle_1   | moodle 11:13:19.93 INFO  ==> Persisting Moodle installation
moodle_1   | moodle 11:13:32.99 INFO  ==> ** Moodle setup finished! **
moodle_1   | 
moodle_1   | moodle 11:13:33.00 INFO  ==> ** Starting cron **
moodle_1   | moodle 11:13:33.03 INFO  ==> ** Starting Apache **
moodle_1   | [Thu Dec 24 11:13:33.201475 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Thu Dec 24 11:13:33.201800 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Thu Dec 24 11:13:33.226618 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Thu Dec 24 11:13:33.226977 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
moodle_1   | [Thu Dec 24 11:13:33.241820 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.25 configured -- resuming normal operations
moodle_1   | [Thu Dec 24 11:13:33.241848 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
^CGracefully stopping... (press Ctrl+C again to force)
```

```
[rafa@localhost bitnami-docker-moodle]$ docker images 
REPOSITORY        TAG              IMAGE ID       CREATED        SIZE
bitnami/moodle    3-debian-10      8914e9e524ca   16 hours ago   1.16GB
bitnami/mariadb   10.5-debian-10   eb8dde8feee9   17 hours ago   331MB

```


 It seems that the kernel need to have the getrandom system function.
 Could you compile and run this small C++ program ?
```
$ cat test.cpp

#include <iostream>
#include <unistd.h>
#include <sys/syscall.h>
#include <linux/random.h>

int main() {
  unsigned long int s;
  syscall(SYS_getrandom, &s, sizeof(unsigned long int), 0);
  std::cout << "The seed is: " << s << "." << std::endl;
}

$ c++ test.cpp
$ ./a.out
The seed is: 14337317558287481162.
```
It should return a random number.

**Comment by 3mandd** [comment] 2020-12-25 19:36
> @rafariossaa are you using centos too ?

Debian bullseye.
 
>@Ray-Eldath how can nginx solve the problem?"

I have a working web server again minus 1/2 day spent trying to figure out what was wrong with apache2 (which I'm unlikely to use anymore after trying nginx)

**Comment by rafariossaa** [comment] 2020-12-28 10:34
@3mandd ,
 Do you mind trying the small c++ program ?, That could help up to solve this issue.
 @julian3xl , Did you have a chance to try what I indicated ?

**Comment by 3mandd** [comment] 2021-01-19 08:58
> @3mandd ,
> Do you mind trying the small c++ program ?, That could help up to solve this issue.
> @julian3xl , Did you have a chance to try what I indicated ?

Yes sure.

**Comment by FrommyMind** [comment] 2021-03-12 02:15
Docker  Verion

> Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:34:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


K8s Version

> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Helm Version

> version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

OS Version
> Linux k8s-testnode1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Install with helm
`helm install my-wordpress stable/wordpress`


Pod's error logs
kubectl logs  my-wordpress-55497c5746-p298p -f

> Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre INFO  ==> Preparing Apache environment
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at my-wordpress-mariadb:3306
mysql-c INFO  MySQL server listening and working at my-wordpress-mariadb:3306
wordpre INFO  Preparing WordPress environment
wordpre INFO
wordpre INFO  ########################################################################
wordpre INFO   Installation parameters for wordpress:
wordpre INFO     First Name: FirstName
wordpre INFO     Last Name: LastName
wordpre INFO     Username: user
wordpre INFO     Password: **********
wordpre INFO     Email: user@example.com
wordpre INFO     Blog Name: User's Blog!
wordpre INFO     Table Prefix: wp_
wordpre INFO   (Passwords are not shown for security reasons)
wordpre INFO  ########################################################################
wordpre INFO
nami    INFO  wordpress successfully initialized
INFO  ==> Starting wordpress...
nami    ERROR Unable to start com.bitnami.apache: [Fri Mar 12 02:08:48.540818 2021] [:crit] [pid 101] (38)Function not implemented: AH00141: Could not initialize random number generator



Image Version 
>bitnami/wordpress                        5.6.2-debian-10-r8      ae02224fa119   7 days ago      1.55GB
bitnami/mariadb                          10.3.22-debian-10-r27   86f8545f6c09   12 months ago   285MB


@rafariossaa 
cat test.cpp
>#include <iostream>
#include <unistd.h>
#include <sys/syscall.h>
#include <linux/random.h>
int main() {
  unsigned long int s;
  syscall(SYS_getrandom, &s, sizeof(unsigned long int), 0);
  std::cout << "The seed is: " << s << "." << std::endl;
}

>c++ test.cpp
 ./a.out
The seed is: 4196368.
c++ test.cpp
./a.out
The seed is: 4196368.
./a.out
The seed is: 4196368.
./a.out
The seed is: 4196368.

The result are same.

**Comment by rafariossaa** [comment] 2021-03-12 16:56
I think that that is the reason of the error you got. You always get the same number and the number should be different in each run.
```
$ c++ test.cpp 

17:53 $ ./a.out 
The seed is: 10068184427606828901.
17:53 $ ./a.out 
The seed is: 8276396664563020420.
17:53 $ ./a.out 
The seed is: 3692925810329965300.
17:53 $ ./a.out 
The seed is: 3598542987125579261.
17:53 $ ./a.out 
The seed is: 7971581794950177591.
17:53 $ ./a.out 
The seed is: 13599367870677168523.
```
That it related to you host kernel.

**Comment by hyunwooklim** [comment] 2021-03-17 01:32
you should update your kernel ; like this 

yum update -y kernel

yum list kernel

grub2-editenv list

grub2-set-default 0

systemctl reboot

**Comment by rafariossaa** [comment] 2021-03-17 17:15
Hi,
  Thanks @hyunwooklim for providing a hint.
  @FrommyMind , could you try what @hyunwooklim suggested ?

**Comment by FrommyMind** [comment] 2021-03-22 02:27
> Hi,
> Thanks @hyunwooklim for providing a hint.
> @FrommyMind , could you try what @hyunwooklim suggested ?

After do what @hyunwooklim  said, the `a.out` produced random result .

**Comment by rafariossaa** [comment] 2021-03-22 08:45
Hi,
  In that case, could you try again the moodle image ?

**Comment by FrommyMind** [comment] 2021-03-22 09:01
> Hi,
> In that case, could you try again the moodle image ?
> Let's see if that fixes your issue.

I am sorry about that, My test env was been distoried,  I will set up a new env and test it again. I will update information soon or later.

**Comment by FrommyMind** [comment] 2021-03-23 00:42
New environment
This new envrionment was installed by k3s
k3s version
> k3s --version
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

kubectl version
>kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

OS Version
>uname  -a
Linux ansible-2.daniel.com 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Helm Version
>helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

The a.out got random result after I updated the kernel
>./a.out 
The seed is: 7846649277170683763.
./a.out 
The seed is: 16347907850732614658.
 ./a.out 
The seed is: 8967163686398506763.

Use helm install 
>helm install my-wordpress bitnami/wordpress

The pods status
>kubectl get pod
NAME                           READY   STATUS    RESTARTS   AGE
svclb-my-wordpress-lclsr       0/2     Pending   0          10h
svclb-my-wordpress-b8x87       0/2     Pending   0          10h
my-wordpress-mariadb-0         1/1     Running   0          10h
my-wordpress-9f69d688c-cv4ch   1/1     Running   0          10h

The reason why svclb is Pending, I think that's because the kubernetes was installed by k3s [k3s#104](https://github.com/rancher/k3d/issues/104) .

Anyway , @hyunwooklim's idea was work for me. 
@rafariossaa  I think we can close this issue.

**Comment by rafariossaa** [comment] 2021-03-23 16:19
Hi @FrommyMind ,
  Thanks for checking it and sharing your results.
  I am happy the issue is solved for you.
  I am closing the issue, don't hesitate to reopen it if needed.

**Closed by rafariossaa** 2021-03-23 16:19 UTC
