### ISSUE TITLE
New install fails on postInstallation

### ISSUE THREAD

**Issue by mickey1928geo** [bitnami/bitnami-docker-moodle#114] opened 2020-04-14 19:57 UTC
New Moodle deployment using persistent storage via docker-compose.  Upon install, the Moodle container stops.  I've followed the install via docker logs, and got the following from moodle_moodle_1:

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
moodle  INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle  INFO  Running Moodle install. Please be patient...
Error executing 'postInstallation': Value to set is empty

Ownership is set on my folders via chmod -R 1001:1001
- /opt/moodle/moodle_data
- /opt/moodle/mariadb

Docker version 1.40

docker-compose.yml:

version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_ROOT_PASSWORD=mypassword
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - /opt/moodle/mariadb:/bitnami/mariadb
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=mypassword
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - SMTP_HOST=mail.mydomain.us
      - SMTP_PORT=25
    ports:
      - '8085:80'
    volumes:
      - /opt/moodle/moodle_data:/bitnami
    depends_on:
      - mariadb

---

Any suggestions?

**Comment by Mauraza** [comment] 2020-04-15 08:49
Hi @mickey1928geo,

thanks for reporting!!, we will investigate, and we will update the issue with more information.

**Comment by numericalatina** [comment] 2020-04-24 18:58
I'm experiencing a very similar issue, it creates the database and then crashes leaving it empty. Specific error is a bit different though. Here are the logs:

```
Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at aula_ideas_db:3306
mysql-c INFO  MySQL server listening and working at aula_ideas_db:3306
mysql-c INFO  ==> Creating database bitnami_moodle...
mysql-c INFO  ==> Found existing user dWq5lLudjh. Skipping user creation...
mysql-c INFO  ==> Granting access to dWq5lLudjh to the database bitnami_moodle...
mysql-c INFO 
mysql-c INFO  ########################################################################
mysql-c INFO   Installation parameters for mysql-client:
mysql-c INFO     Database User created: dWq5lLudjh
mysql-c INFO     Database Name created: bitnami_moodle
mysql-c INFO     Database Password created: **********
mysql-c INFO     Database Host: aula_ideas_db
mysql-c INFO     Database Port: 3306
mysql-c INFO     Database Root User: root
mysql-c INFO     Database Root Password: **********
mysql-c INFO   (Passwords are not shown for security reasons)
mysql-c INFO  ########################################################################
mysql-c INFO 
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
moodle  INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at aula_ideas_db:3306
mysql-c INFO  MySQL server listening and working at aula_ideas_db:3306
Error executing 'postInstallation': Config table does not contain version, can not continue, sorry.
```

**Comment by numericalatina** [comment] 2020-04-24 19:35
Ok I "turned around" this by deleting everything at the moodle volume, which is fine for me because it was a brand new install... 
Apparently initialization fails because of pre-existing files, which should be being created.

**Comment by beltran-rubo** [comment] 2020-04-29 11:14
Thanks for posting your solution. We could not reproduce it on our side, it is possible that the first installation failed for any reason and that ends up in a Moodle volume that was not properly initialized. Moodle application takes some time to populate the database the first time and to perform the installation.

I will close this issue, please re-open if you find any issue.

**Closed by beltran-rubo** 2020-04-29 11:14 UTC
