### ISSUE TITLE
Sample Docker-Compose file won't survive restarts

### ISSUE THREAD

**Issue by vaughnmb** [bitnami/bitnami-docker-moodle#54] opened 2017-04-06 18:19 UTC
Example docker-compose file won't survive restarts.  Gives a 503 when you try to open Moodle in a browser after you "docker-compose down" and then "docker-compose up" the file.  You get this error message on the screen. " error/An error occurred whilst communicating with the server "

**Steps to reproduce the issue:**
1.  Download example docker-compose file from docker hub site:  curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml
2. docker-compose up
3. open the front page  http://127.0.0.1
4. docker-compose down
5. docker-compose up
6. open the front page  http://127.0.0.1
7.  You get this error message on the screen " error/An error occurred whilst communicating with the server "

**Describe the results you received:**
Docker-Compose file doesn't survive restarts

**Describe the results you expected:**
Docker-Compose file to survive restarts

**Additional information you deem important (e.g. issue happens only occasionally):**

- Output of `docker version`:

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb2265
 Built:        Thu Feb 23 10:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb2265
 Built:        Thu Feb 23 10:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false


```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1716
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1390
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 411z2fpbxhcxxfmi7s7lqcfp6
 Is Manager: true
 ClusterID: cy9txa4whmlxehhf335bsxydv
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.107
 Manager Addresses:
  192.168.0.107:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Linux Mint 18.1
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: trainspotting
ID: P7TS:ZLYM:ZXHC:TF2C:BPQP:JIJN:5WWJ:M7VW:KVLN:Z7IL:VGMW:XIOI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016


```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment] 2017-04-07 11:05
I was unable to reproduce your issue. Could you please check that you don't have any other MySQL Docker Container running in your system? Run the commands below to see if the issue disappears:

```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -qf dangling=true)
docker-compose up
```

Then continue with the steps you described:

```
docker-compose down
docker-compose up
```

Access http://127.0.0.1

**Comment by vaughnmb** [comment] 2017-04-07 16:44
I ran your suggested steps and I still have the same problem.  Here is the docker log output from the Moodle container.  This output is after the docker-compose file has been started, stopped, and started again.  All I did was go to http://127.0.0.1  after the "start, stop, start" of docker-compose

$ docker logs moodle_moodle_1 

Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing moodle
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle  INFO  Configuring Cron Jobs...
moodle  INFO 
moodle  INFO  ########################################################################
moodle  INFO   Installation parameters for moodle:
moodle  INFO     Persisted data and properties have been restored.
moodle  INFO     Any input specified will not take effect.
moodle  INFO   (Passwords are not shown for security reasons)
moodle  INFO  ########################################################################
moodle  INFO 
nami    INFO  moodle successfully initialized
INFO  ==> Starting moodle...

172.19.0.1 - - [07/Apr/2017:16:40:26 +0000] "GET / HTTP/1.1" 503 544
172.19.0.1 - - [07/Apr/2017:16:40:26 +0000] "GET /favicon.ico HTTP/1.1" 404 209

**Comment by vaughnmb** [comment] 2017-04-07 16:52
Also, I had another co-worker try it out.  He encountered the same problem I did.

**Comment by sameersbn** [comment] 2017-04-10 04:00
@juan131 @vaughnmb I can confirm this issue (see screenshot below).

On enabling the nami debugger I noticed the following errors in the moodle container logs

```logs
moodle_1   | nami    INFO  Initializing moodle
moodle_1   | moodle  DEBUG Existing installation, restoring...
moodle_1   | moodle  TRACE [restorePersistedData] Restoring /bitnami/moodle/config.php to /opt/bitnami/moodle/config.php
moodle_1   | mysql-c INFO  Trying to connect to MySQL server
moodle_1   | mysql-c INFO  Found MySQL server listening at mariadb:3306
moodle_1   | mysql-c TRACE [canConnect] Testing connection with 'bn_moodle' user
moodle_1   | mysql-c TRACE [showDatabases] Getting databases for 'bn_moodle' user
moodle_1   | mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -ubn_moodle -pEkT6yBq3ef -e SHOW DATABASES;
moodle_1   | mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_moodle\ninformation_schema\n","stderr":""}
moodle_1   | mysql-c TRACE [showDatabases] Databases: undefined
moodle_1   | mysql-c TRACE [canConnect] Connection with 'bn_moodle' user is successful
moodle_1   | mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle_1   | php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php admin/cli/upgrade.php,--non-interactive,--allow-unstable
```

To be precise, the following lines identify the issue

```
moodle_1   | mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -ubn_moodle -pEkT6yBq3ef -e SHOW DATABASES;
moodle_1   | mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_moodle\ninformation_schema\n","stderr":""}
moodle_1   | mysql-c TRACE [showDatabases] Databases: undefined
```

![error](https://cloud.githubusercontent.com/assets/410147/24844523/d709790e-1dc8-11e7-837c-092ff68032e1.png)

Hope you find this information useful to debug and resolve the issue.

Cheers :beers:

**Comment by juan131** [comment] 2017-04-11 13:05
@sameersbn @vaughnmb The problem is not related with the connection to MySQL. The problem is related with the cookies/sessions. If you open a new tab on your browser cleaning up the cookies, the issue disappears.

I am still investigating why the sessions information is lost when restoring the container.

**Comment by juan131** [comment] 2017-04-17 14:00
@vaughnmb we just released a new revision (3.2.2-r2) fixing this issue. Could you please confirm that the problem disappeared using the latest revision?

**Comment by vaughnmb** [comment] 2017-04-17 15:18
@juan131 It worked.  Thanks for the fix.

**Comment by juan131** [comment] 2017-04-17 15:48
@vaughnmb @sameersbn I proceed to close the issue.

Please reopen it if you find problems when restarting again.

**Closed by juan131** 2017-04-17 15:48 UTC
